version: '3'
services:
  backend:
    build:
      context: ./backend
    expose:
      - 3000
  frontend:
    build:
      context: ./frontend
    expose:
      - 80
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
